export const COMPANIES = [
  // Bulge Bracket Investment Banks
  'Goldman Sachs',
  'Morgan Stanley',
  'JPMorgan Chase',
  'Bank of America',
  'Citigroup',
  'Deutsche Bank',
  'Credit Suisse',
  'UBS',
  'Barclays',
  'Wells Fargo',
  // Elite Boutique Investment Banks
  'Lazard',
  'Evercore',
  'Centerview Partners',
  'Moelis & Company',
  'PJT Partners',
  'Perella Weinberg Partners',
  'Guggenheim Partners',
  'Houlihan Lokey',
  'Greenhill & Co',
  'Rothschild & Co',
  'Qatalyst Partners',
  'Allen & Company',
  // Private Equity Firms
  'Blackstone',
  'KKR',
  'Carlyle Group',
  'Apollo Global Management',
  'TPG Capital',
  'Bain Capital',
  'Warburg Pincus',
  'General Atlantic',
  'Silver Lake Partners',
  'Vista Equity Partners',
  'Thoma Bravo',
  'Advent International',
  'Hellman & Friedman',
  'Clayton, Dubilier & Rice',
  'Leonard Green & Partners',
  'GTCR',
  'Permira',
  'Cinven',
  'EQT Partners',
  'CVC Capital Partners',
  // Consulting Firms (MBB + Tier 2)
  'McKinsey & Company',
  'Boston Consulting Group',
  'Bain & Company',
  'Deloitte',
  'PwC',
  'EY',
  'KPMG',
  'Accenture',
  'Oliver Wyman',
  'Strategy&',
  'Roland Berger',
  'Kearney',
  'LEK Consulting',
  'ZS Associates',
  'AlixPartners',
  'FTI Consulting',
  'Huron Consulting',
  'Booz Allen Hamilton',
  'Capgemini',
  'IBM Consulting',
  // Asset Management Firms
  'BlackRock',
  'Vanguard',
  'Fidelity Investments',
  'State Street Global Advisors',
  'T. Rowe Price',
  'Capital Group',
  'Wellington Management',
  'Franklin Templeton',
  'Invesco',
  'Northern Trust',
  'AllianceBernstein',
  'Eaton Vance',
  'Janus Henderson',
  'PIMCO',
  'AQR Capital Management',
  'Two Sigma',
  'Renaissance Technologies',
  'Bridgewater Associates',
  'Citadel',
  'Millennium Management',
  // Other Finance Firms
  'Raymond James',
  'Jefferies',
  'Stifel',
  'Piper Sandler',
  'Cowen',
  'William Blair',
  'Stephens Inc',
  'Baird',
  'Robert W. Baird',
  'Tudor Investment Corporation',
  'D.E. Shaw',
  'Point72',
] as const;

export const ROLES = [
  'Analyst',
  'Associate',
  'Vice President',
  'Director',
  'Managing Director',
  'Investment Banking',
  'Private Equity',
  'Consulting',
  'Asset Management',
  'Sales & Trading',
  'Research',
  'Wealth Management',
] as const;

export const UNIVERSITIES = [
  // Ivy League
  'Harvard University',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Cornell University',
  'Dartmouth College',
  'Brown University',
  // Top Private Universities
  'Stanford University',
  'MIT',
  'Duke University',
  'Northwestern University',
  'University of Chicago',
  'Vanderbilt University',
  'Rice University',
  'Emory University',
  'Notre Dame',
  'Georgetown University',
  'Johns Hopkins University',
  'Carnegie Mellon University',
  'Washington University in St. Louis',
  'Wake Forest University',
  'Boston University',
  'Tufts University',
  'Brandeis University',
  'Case Western Reserve University',
  'Tulane University',
  // Top Public Universities
  'UC Berkeley',
  'UCLA',
  'University of Michigan',
  'University of Virginia',
  'University of North Carolina at Chapel Hill',
  'University of Texas at Austin',
  'University of Wisconsin-Madison',
  'University of Illinois at Urbana-Champaign',
  'University of Washington',
  'University of California, San Diego',
  'University of California, Davis',
  'University of California, Santa Barbara',
  'University of California, Irvine',
  'University of Georgia',
  'University of Florida',
  'Penn State University',
  'Ohio State University',
  'Indiana University',
  'University of Maryland',
  'University of Minnesota',
  'Purdue University',
  'Rutgers University',
  'University of Connecticut',
  'Arizona State University',
  'University of Arizona',
  'Texas A&M University',
  'University of Southern California',
  'University of Miami',
  'Florida State University',
  'Clemson University',
  'Virginia Tech',
  'North Carolina State University',
  'University of South Carolina',
  'Auburn University',
  'University of Alabama',
  'University of Tennessee',
  'University of Kentucky',
  'Louisiana State University',
  'University of Arkansas',
  'Mississippi State University',
  'University of Mississippi',
  // Other Target Schools
  'New York University',
  'Boston College',
  'Villanova University',
  'Lehigh University',
  'Babson College',
  'Bentley University',
  'Baruch College',
  'University of Richmond',
  'College of William & Mary',
  'James Madison University',
  'University of Delaware',
  'University of Vermont',
  'University of New Hampshire',
  'University of Maine',
  'University of Rhode Island',
] as const;

export const LOCATIONS = [
  '',
  'New York',
  'San Francisco',
  'Los Angeles',
  'Chicago',
  'Boston',
  'London',
  'Hong Kong',
  'Singapore',
  'Dallas',
  'Houston',
  'Atlanta',
  'Charlotte',
  'Miami',
  'Washington DC',
  'Seattle',
  'Denver',
] as const;

export const EMAIL_TEMPLATES = [
  {
    id: 'default',
    name: 'Default',
    subject: 'Reaching out from {university}',
    body: `Hi {first_name},

I hope you are doing well. My name is {user_name} and I am a {classification} pursuing my {major} at {university}. I am interested in {career} and would love to grab 10-15 minutes on the phone with you to hear about your experiences at {company}.

In case it's helpful to provide more context on my background, I have attached my resume below for your reference. I look forward to hearing from you.

Warm regards,
{user_name}`,
  },
] as const;

export type Company = (typeof COMPANIES)[number];
export type Role = (typeof ROLES)[number];
export type University = (typeof UNIVERSITIES)[number];
export type Location = (typeof LOCATIONS)[number];
export type EmailTemplate = (typeof EMAIL_TEMPLATES)[number];
