export const INDUSTRIES = ['Banking', 'Consulting', 'PM'] as const;

// Banking companies
export const BANKING_COMPANIES = [
  'Goldman Sachs',
  'Morgan Stanley',
  'JPMorgan Chase',
  'Bank of America',
  'Citigroup',
  'Barclays',
  'Deutsche Bank',
  'UBS',
  'Credit Suisse',
  'Wells Fargo',
  'Lazard',
  'Evercore',
  'Centerview Partners',
  'Moelis & Company',
  'PJT Partners',
  'Perella Weinberg Partners',
  'Guggenheim Partners',
  'Houlihan Lokey',
  'Greenhill & Co',
  'Rothschild & Co',
  'Jefferies',
  'RBC Capital Markets',
  'HSBC',
  'BNP Paribas',
] as const;

// Only companies with verified email patterns
export const CONSULTING_COMPANIES = [
  'McKinsey & Company',
  'Boston Consulting Group',
  'Bain & Company',
  'Deloitte',
  'PwC',
  'EY',
  'KPMG',
  'Accenture',
  'Oliver Wyman',
  'Kearney',
  'LEK Consulting',
  'ZS',
  'Huron',
] as const;

// Only companies with verified email patterns
export const PM_COMPANIES = [
  'Google',
  'NVIDIA',
  'Microsoft',
  'Stripe',
  'Meta',
  'Adobe',
  'Amazon',
  'Airbnb',
  'Slack',
  'Atlassian',
  'Shopify',
] as const;

export const COMPANIES_BY_INDUSTRY: Record<string, readonly string[]> = {
  Banking: BANKING_COMPANIES,
  Consulting: CONSULTING_COMPANIES,
  PM: PM_COMPANIES,
};

export const COMPANIES = [
  // Bulge Bracket Investment Banks
  'Goldman Sachs',
  'Morgan Stanley',
  'JPMorgan Chase',
  'Bank of America',
  'Citigroup',
  'Deutsche Bank',
  'Credit Suisse',
  'UBS',
  'Barclays',
  'Wells Fargo',
  // Elite Boutique Investment Banks
  'Lazard',
  'Evercore',
  'Centerview Partners',
  'Moelis & Company',
  'PJT Partners',
  'Perella Weinberg Partners',
  'Guggenheim Partners',
  'Houlihan Lokey',
  'Greenhill & Co',
  'Rothschild & Co',
  'Qatalyst Partners',
  'Allen & Company',
  // Private Equity Firms
  'Blackstone',
  'KKR',
  'Carlyle Group',
  'Apollo Global Management',
  'TPG Capital',
  'Bain Capital',
  'Warburg Pincus',
  'General Atlantic',
  'Silver Lake Partners',
  'Vista Equity Partners',
  'Thoma Bravo',
  'Advent International',
  'Hellman & Friedman',
  'Clayton, Dubilier & Rice',
  'Leonard Green & Partners',
  'GTCR',
  'Permira',
  'Cinven',
  'EQT Partners',
  'CVC Capital Partners',
  // Consulting Firms (MBB + Tier 2)
  'McKinsey & Company',
  'Boston Consulting Group',
  'Bain & Company',
  'Deloitte',
  'PwC',
  'EY',
  'KPMG',
  'Accenture',
  'Oliver Wyman',
  'Strategy&',
  'Roland Berger',
  'Kearney',
  'LEK Consulting',
  'ZS Associates',
  'AlixPartners',
  'FTI Consulting',
  'Huron Consulting',
  'Booz Allen Hamilton',
  'Capgemini',
  'IBM Consulting',
  // Asset Management & Hedge Funds
  'BlackRock',
  'Vanguard',
  'Fidelity Investments',
  'State Street Global Advisors',
  'T. Rowe Price',
  'Capital Group',
  'Wellington Management',
  'Franklin Templeton',
  'Invesco',
  'Northern Trust',
  'AllianceBernstein',
  'Eaton Vance',
  'Janus Henderson',
  'PIMCO',
  'AQR Capital Management',
  'Two Sigma',
  'Renaissance Technologies',
  'Bridgewater Associates',
  'Citadel',
  'Millennium Management',
  // Other Finance
  'Raymond James',
  'Jefferies',
  'Stifel',
  'Piper Sandler',
  'Cowen',
  'William Blair',
  'Stephens Inc',
  'Baird',
  'Robert W. Baird',
  'Tudor Investment Corporation',
  'D.E. Shaw',
  'Point72',
  'Charles Schwab',
  'TD Ameritrade',
  'Interactive Brokers',
  'Robinhood',
  'SoFi',
  // Tech — Large Cap
  'Google',
  'Apple',
  'Microsoft',
  'Amazon',
  'Meta',
  'NVIDIA',
  'Netflix',
  'Salesforce',
  'Oracle',
  'Intel',
  'Cisco',
  'IBM',
  'Adobe',
  'SAP',
  'VMware',
  'Qualcomm',
  'Texas Instruments',
  'Broadcom',
  'AMD',
  'Intuit',
  // Tech — Growth & Mid Cap
  'Uber',
  'Lyft',
  'Airbnb',
  'DoorDash',
  'Instacart',
  'Stripe',
  'Coinbase',
  'Palantir',
  'Snowflake',
  'Databricks',
  'ServiceNow',
  'Workday',
  'Atlassian',
  'Shopify',
  'Slack',
  'Zoom',
  'Twilio',
  'Square',
  'Block',
  'Plaid',
  'Figma',
  'Notion',
  'Airtable',
  'Rippling',
  'Ramp',
  'Brex',
  'Scale AI',
  'Anduril',
  'SpaceX',
  'OpenAI',
  'Anthropic',
  // Healthcare & Pharma
  'Johnson & Johnson',
  'Pfizer',
  'Merck',
  'UnitedHealth Group',
  'CVS Health',
  'Abbott Laboratories',
  'Eli Lilly',
  'AbbVie',
  'Amgen',
  'Gilead Sciences',
  'Bristol-Myers Squibb',
  'Medtronic',
  'Thermo Fisher Scientific',
  'Danaher',
  'Stryker',
  'Becton Dickinson',
  'Baxter International',
  'Moderna',
  'Regeneron',
  'Biogen',
  // Energy
  'ExxonMobil',
  'Chevron',
  'Shell',
  'BP',
  'ConocoPhillips',
  'Phillips 66',
  'Valero Energy',
  'Marathon Petroleum',
  'Schlumberger',
  'Halliburton',
  'Baker Hughes',
  'Pioneer Natural Resources',
  'EOG Resources',
  'Devon Energy',
  'NextEra Energy',
  // Consumer & Retail
  'Walmart',
  'Target',
  'Costco',
  'Home Depot',
  'Nike',
  'Procter & Gamble',
  'Coca-Cola',
  'PepsiCo',
  'Unilever',
  'Colgate-Palmolive',
  'Estee Lauder',
  'LVMH',
  'Starbucks',
  'McDonald\'s',
  'Yum! Brands',
  'Chipotle',
  'Lululemon',
  'Ralph Lauren',
  // Media & Entertainment
  'Walt Disney',
  'Warner Bros. Discovery',
  'NBCUniversal',
  'Paramount',
  'Sony',
  'Spotify',
  'Live Nation',
  'Electronic Arts',
  // Telecom
  'AT&T',
  'Verizon',
  'T-Mobile',
  'Comcast',
  // Aerospace & Defense
  'Boeing',
  'Lockheed Martin',
  'Raytheon',
  'Northrop Grumman',
  'General Dynamics',
  'L3Harris Technologies',
  'BAE Systems',
  // Industrial & Manufacturing
  'General Electric',
  '3M',
  'Honeywell',
  'Caterpillar',
  'John Deere',
  'Parker Hannifin',
  'Emerson Electric',
  'Illinois Tool Works',
  // Automotive
  'Tesla',
  'Ford',
  'General Motors',
  'Toyota',
  'Rivian',
  'Lucid Motors',
  // Real Estate
  'CBRE',
  'JLL',
  'Cushman & Wakefield',
  'Prologis',
  'Simon Property Group',
  // Insurance
  'Berkshire Hathaway',
  'Marsh McLennan',
  'Aon',
  'Willis Towers Watson',
  'AIG',
  'MetLife',
  'Prudential Financial',
  // Transportation & Logistics
  'FedEx',
  'UPS',
  'Union Pacific',
  'Delta Air Lines',
  'United Airlines',
  'Southwest Airlines',
] as const;

export const ROLES = [
  // General
  'Recruiter',
  'Intern',
  'Analyst',
  'Associate',
  'Manager',
  'Senior Manager',
  'Director',
  'Vice President',
  'Senior Vice President',
  'Managing Director',
  'Partner',
  'Principal',
  // Finance-Specific
  'Investment Banking Analyst',
  'Investment Banking Associate',
  'Private Equity Analyst',
  'Private Equity Associate',
  'Sales & Trading',
  'Research Analyst',
  'Wealth Management',
  'Portfolio Manager',
  'Trader',
  'Quantitative Analyst',
  'Risk Analyst',
  'Financial Analyst',
  'Accountant',
  'Auditor',
  'Actuary',
  // Consulting-Specific
  'Business Analyst',
  'Consultant',
  'Senior Consultant',
  'Engagement Manager',
  'Case Team Leader',
  'Project Leader',
  // Engineering & Tech
  'Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full Stack Engineer',
  'Data Engineer',
  'Machine Learning Engineer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'QA Engineer',
  'Security Engineer',
  'Engineering Manager',
  'Solutions Engineer',
  'Solutions Architect',
  'Technical Program Manager',
  // Product & Design
  'Product Manager',
  'Senior Product Manager',
  'Associate Product Manager',
  'Product Designer',
  'UX Designer',
  'UX Researcher',
  'UI Designer',
  'Graphic Designer',
  // Data & Analytics
  'Data Scientist',
  'Data Analyst',
  'Business Intelligence Analyst',
  'Analytics Manager',
  // Sales & Business Development
  'Account Executive',
  'Sales Development Representative',
  'Business Development Representative',
  'Account Manager',
  'Customer Success Manager',
  'Sales Manager',
  'Sales Engineer',
  // Marketing
  'Marketing Manager',
  'Brand Manager',
  'Product Marketing Manager',
  'Growth Marketing Manager',
  'Content Strategist',
  'Social Media Manager',
  'Marketing Analyst',
  // Operations & Supply Chain
  'Operations Manager',
  'Supply Chain Manager',
  'Logistics Manager',
  'Project Manager',
  'Program Manager',
  'Chief of Staff',
  // Human Resources
  'HR Manager',
  'Talent Acquisition',
  'People Operations',
  'Compensation Analyst',
  // Legal & Compliance
  'Attorney',
  'Legal Counsel',
  'Compliance Officer',
  'Paralegal',
  // Healthcare
  'Clinical Research Associate',
  'Regulatory Affairs',
  'Medical Science Liaison',
  // Communications & PR
  'Communications Manager',
  'Public Relations Manager',
  'Corporate Communications',
] as const;

// Company-specific roles
export const ROLES_BY_COMPANY: Record<string, readonly string[]> = {
  // Banking Companies
  'Goldman Sachs': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Executive Director',
    'Managing Director',
  ],
  'Morgan Stanley': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Executive Director',
    'Managing Director',
  ],
  'JPMorgan Chase': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Executive Director',
    'Managing Director',
  ],
  'Bank of America': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Citigroup': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Barclays': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Deutsche Bank': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'UBS': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Director',
    'Executive Director',
    'Managing Director',
  ],
  'Credit Suisse': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Wells Fargo': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Lazard': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Evercore': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Senior Vice President',
    'Senior Managing Director',
  ],
  'Centerview Partners': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Principal',
    'Partner',
  ],
  'Moelis & Company': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'PJT Partners': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Partner',
  ],
  'Perella Weinberg Partners': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Partner',
  ],
  'Guggenheim Partners': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Houlihan Lokey': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Greenhill & Co': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Rothschild & Co': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'Jefferies': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'RBC Capital Markets': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'HSBC': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  'BNP Paribas': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
  ],
  // Consulting Companies
  'McKinsey & Company': [
    'Recruiter',
    'Business Analyst',
    'Senior Business Analyst',
    'Associate',
    'Engagement Manager',
    'Associate Principal',
    'Partner',
  ],
  'Boston Consulting Group': [
    'Recruiter',
    'Associate',
    'Senior Associate',
    'Consultant',
    'Project Leader',
    'Principal',
    'Partner',
    'Managing Director & Partner',
  ],
  'Bain & Company': [
    'Recruiter',
    'Associate',
    'Senior Associate',
    'Consultant',
    'Case Team Leader',
    'Manager',
    'Principal',
    'Partner',
  ],
  'Deloitte': [
    'Recruiter',
    'Analyst',
    'Consultant',
    'Senior Consultant',
    'Manager',
    'Senior Manager',
    'Partner',
  ],
  'Accenture': [
    'Recruiter',
    'Analyst',
    'Consultant',
    'Senior Consultant',
    'Manager',
    'Senior Manager',
    'Director',
  ],
  'Strategy&': [
    'Recruiter',
    'Associate',
    'Senior Associate',
    'Manager',
    'Director',
    'Partner',
  ],
  'KPMG': [
    'Recruiter',
    'Analyst',
    'Consultant',
    'Senior Consultant',
    'Manager',
    'Senior Manager',
    'Partner',
  ],
  'EY': [
    'Recruiter',
    'Associate Consultant',
    'Senior Consultant',
    'Manager',
    'Associate Partner',
    'Partner',
  ],
  'LEK Consulting': [
    'Recruiter',
    'Associate',
    'Consultant',
    'Manager',
    'Senior Manager',
    'Principal',
    'Partner',
  ],
  'PwC': [
    'Recruiter',
    'Associate',
    'Senior Associate',
    'Manager',
    'Senior Manager',
    'Director',
    'Partner',
  ],
  'Oliver Wyman': [
    'Recruiter',
    'Analyst',
    'Senior Consultant',
    'Associate',
    'Engagement Manager',
    'Principal',
    'Director',
    'Partner',
  ],
  'Roland Berger': [
    'Recruiter',
    'Business Analyst',
    'Junior Consultant',
    'Consultant',
    'Senior Consultant',
    'Project Manager',
    'Principal',
    'Partner',
  ],
  'Kearney': [
    'Recruiter',
    'Business Analyst',
    'Senior Business Analyst',
    'Associate',
    'Manager',
    'Principal',
    'Associate Partner',
    'Partner',
  ],
  'ZS': [
    'Recruiter',
    'Associate',
    'Associate Consultant',
    'Consultant',
    'Manager',
    'Associate Principal',
    'Principal',
  ],
  'Huron': [
    'Recruiter',
    'Analyst',
    'Associate',
    'Manager',
    'Director',
    'Senior Director',
    'Managing Director',
  ],
  // PM Companies
  'Google': ['Recruiter', 'Associate Product Manager', 'Product Manager'],
  'NVIDIA': ['Recruiter', 'Product Manager', 'Senior Product Manager'],
  'Microsoft': ['Recruiter', 'Program Manager', 'Product Manager'],
  'Stripe': ['Recruiter', 'Product Manager'],
  'Meta': ['Recruiter', 'Rotational Product Manager', 'Product Manager'],
  'Adobe': ['Recruiter', 'Product Manager', 'Senior Product Manager'],
  'Amazon': ['Recruiter', 'Product Manager Technical', 'Product Manager'],
  'Airbnb': ['Recruiter', 'Product Manager'],
  'Slack': ['Recruiter', 'Associate Product Manager', 'Product Manager'],
  'Atlassian': ['Recruiter', 'Associate Product Manager', 'Product Manager'],
  'Shopify': ['Recruiter', 'Product Manager'],
};

export const CLASSIFICATIONS = [
  'Freshman',
  'Sophomore',
  'Junior',
  'Senior',
  'Graduate Student',
  'Master\'s Student',
  'PhD Student',
  'Postgraduate',
] as const;

export const UNIVERSITIES = [
  // Ivy League
  'Harvard University',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Cornell University',
  'Dartmouth College',
  'Brown University',
  // Top Private Universities
  'Stanford University',
  'MIT',
  'Duke University',
  'Northwestern University',
  'University of Chicago',
  'Vanderbilt University',
  'Rice University',
  'Emory University',
  'Notre Dame',
  'Georgetown University',
  'Johns Hopkins University',
  'Carnegie Mellon University',
  'Washington University in St. Louis',
  'Wake Forest University',
  'Boston University',
  'Tufts University',
  'Brandeis University',
  'Case Western Reserve University',
  'Tulane University',
  // Top Public Universities
  'UC Berkeley',
  'UCLA',
  'University of Michigan',
  'University of Virginia',
  'University of North Carolina at Chapel Hill',
  'University of Texas at Austin',
  'University of Wisconsin-Madison',
  'University of Illinois at Urbana-Champaign',
  'University of Washington',
  'University of California, San Diego',
  'University of California, Davis',
  'University of California, Santa Barbara',
  'University of California, Irvine',
  'University of Georgia',
  'University of Florida',
  'Penn State University',
  'Ohio State University',
  'Indiana University',
  'University of Maryland',
  'University of Minnesota',
  'Purdue University',
  'Rutgers University',
  'University of Connecticut',
  'Arizona State University',
  'University of Arizona',
  'Texas A&M University',
  'University of Southern California',
  'University of Miami',
  'Florida State University',
  'Clemson University',
  'Virginia Tech',
  'North Carolina State University',
  'University of South Carolina',
  'Auburn University',
  'University of Alabama',
  'University of Tennessee',
  'University of Kentucky',
  'Louisiana State University',
  'University of Arkansas',
  'Mississippi State University',
  'University of Mississippi',
  // Other Target Schools
  'New York University',
  'Boston College',
  'Villanova University',
  'Lehigh University',
  'Babson College',
  'Bentley University',
  'Baruch College',
  'University of Richmond',
  'College of William & Mary',
  'James Madison University',
  'University of Delaware',
  'University of Vermont',
  'University of New Hampshire',
  'University of Maine',
  'University of Rhode Island',
] as const;

export const LOCATIONS = [
  '',
  'New York',
  'Boston',
  'Philadelphia',
  'Washington DC',
  'Pittsburgh',
  'Baltimore',
  'Atlanta',
  'Charlotte',
  'Miami',
  'Tampa',
  'Nashville',
  'Raleigh',
  'Orlando',
  'Chicago',
  'Detroit',
  'Minneapolis',
  'St. Louis',
  'Kansas City',
  'Columbus',
  'Indianapolis',
  'Cleveland',
  'Dallas',
  'Houston',
  'Austin',
  'San Antonio',
  'Phoenix',
  'Denver',
  'Salt Lake City',
  'New Orleans',
  'San Francisco',
  'Los Angeles',
  'Seattle',
  'San Diego',
  'San Jose',
  'Portland',
  'Palo Alto',
] as const;

export const EMAIL_TEMPLATES = [
  {
    id: 'coffee-chat',
    name: 'Coffee Chat Request',
    subject: '{university} {classification} interested in {industry} at {company}',
    body: `Hello {first_name},

I hope you are doing well. My name is {user_name} and I am a {classification} pursuing my {major} at {university}. I am interested in {career} and would love to grab 10-15 minutes on the phone with you to hear about your experiences at {company}.

In case it's helpful to provide more context on my background, I have attached my resume below for your reference. I look forward to hearing from you.

Warm regards,
{user_name}`,
  },
  {
    id: 'interview-thank-you',
    name: 'Interview Thank You Note',
    subject: 'Thank you for the interview - {role} at {company}',
    body: `Hi {first_name},

Thank you for taking the time to tell me about the {role} position at {company} and for the opportunity to interview {interview_date}.

I especially enjoyed learning about {topics_discussed}. It was great getting a clearer picture of what the role actually looks like day-to-day.

Please let me know if there's anything else I can provide. Hope you have a great rest of your week!

Best,
{user_name}`,
  },
] as const;

export type Industry = (typeof INDUSTRIES)[number];
export type Company = (typeof COMPANIES)[number];
export type Role = (typeof ROLES)[number];
export type Classification = (typeof CLASSIFICATIONS)[number];
export type University = (typeof UNIVERSITIES)[number];
export type Location = (typeof LOCATIONS)[number];
export type EmailTemplate = (typeof EMAIL_TEMPLATES)[number];

// Email Credit System
export const EMAIL_LIMITS = {
  FREE_LIFETIME_LIMIT: 2, // Free users get 2 emails total (lifetime)
  CREDITS_ON_INVITE_SENT: 10,
  MAX_INVITES_PER_DAY: 1,
  MAX_CREDITS: 10,
} as const;

// Subscription Pricing
export const SUBSCRIPTION_PRICING = {
  MONTHLY_PRICE: 20, // $20/month recurring
  UPFRONT_PRICE_PER_MONTH: 10, // $10/month when paid upfront
  MIN_UPFRONT_MONTHS: 4,
  MAX_UPFRONT_MONTHS: 12,
} as const;
